# Generated by Django 3.2 on 2021-04-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('game', models.CharField(choices=[('league', 'League of Legends'), ('valorant', 'Valorant')], default='league', max_length=31, verbose_name='Game')),
                ('ELO', models.BigIntegerField(verbose_name='Hidden ELO')),
                ('logo', models.ImageField(default='card_images/GameRing.png', upload_to='card_images/')),
            ],
        ),
    ]
