# Generated by Django 3.2 on 2021-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ELO',
            field=models.BigIntegerField(default='500', verbose_name='Hidden ELO'),
        ),
    ]
