# Generated by Django 3.1.2 on 2021-04-23 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('game', models.CharField(choices=[('league', 'League of Legends'), ('valorant', 'Valorant')], default='league', max_length=32, verbose_name='game')),
                ('ELO', models.BigIntegerField(default='500', verbose_name='Hidden ELO')),
                ('logo', models.ImageField(default='card_images/GameRing.png', upload_to='card_images/')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('game_name', models.CharField(choices=[('league-of-legends', 'League of Legends'), ('valorant', 'Valorant')], default='league-of-legends', max_length=31, verbose_name='game_name')),
                ('tournament_type', models.CharField(choices=[('round-robin', 'Round Robin'), ('single-elimination', 'Single Elimination'), ('double-Elimination', 'Double Elimination')], default='round-robin', max_length=31, verbose_name='tournament_type')),
                ('grand_finals_modifier', models.CharField(choices=[('single-match', 'Single Match'), ('skip', 'Skip')], default='single-match', max_length=31, verbose_name='grand_finals_modifier')),
                ('url', models.CharField(default='coolmathgames.com', max_length=255, verbose_name='url')),
                ('signup_cap', models.BigIntegerField(verbose_name='signup_cap')),
                ('start_at', models.DateTimeField(verbose_name='start_at')),
                ('hold_third_place_match', models.BooleanField(default=True, verbose_name='hold_third_place_match')),
                ('show_rounds', models.BooleanField(default=True, verbose_name='show_rounds')),
                ('description', models.CharField(max_length=511, verbose_name='description')),
                ('image', models.ImageField(default='card_images/GameRing.png', upload_to='card_images/')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameRing_mod.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GameRing_mod.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
