"""empty message

Revision ID: 7e1c50305622
Revises: 7aa54f4097a5
Create Date: 2021-04-28 16:56:04.785592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1c50305622'
down_revision = '7aa54f4097a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('game_type', sa.String(length=100), nullable=True),
    sa.Column('grand_finals_modifier', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('signup_cap', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.String(length=100), nullable=True),
    sa.Column('hold_third_place_match', sa.Boolean(), nullable=True),
    sa.Column('show_rounds', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('creator', sa.String(length=150), nullable=True),
    sa.Column('entry_fee', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('riotID', sa.String(length=100), nullable=True),
    sa.Column('tagline', sa.String(length=5), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('is_captian', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('tournament')
    # ### end Alembic commands ###
