"""empty message

Revision ID: 955e1b5b17c0
Revises: 
Create Date: 2021-04-24 20:48:03.833693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955e1b5b17c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('creator', sa.String(length=150), nullable=True))
    op.add_column('tournament', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('tournament', sa.Column('game_type', sa.String(length=100), nullable=True))
    op.add_column('tournament', sa.Column('grand_finals_modifier', sa.String(length=100), nullable=True))
    op.add_column('tournament', sa.Column('hold_third_place_match', sa.Boolean(), nullable=True))
    op.add_column('tournament', sa.Column('show_rounds', sa.Boolean(), nullable=True))
    op.add_column('tournament', sa.Column('signup_cap', sa.Integer(), nullable=True))
    op.add_column('tournament', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'url')
    op.drop_column('tournament', 'signup_cap')
    op.drop_column('tournament', 'show_rounds')
    op.drop_column('tournament', 'hold_third_place_match')
    op.drop_column('tournament', 'grand_finals_modifier')
    op.drop_column('tournament', 'game_type')
    op.drop_column('tournament', 'description')
    op.drop_column('tournament', 'creator')
    # ### end Alembic commands ###
