"""empty message

Revision ID: b33e0aed245a
Revises: 8bff1d329615
Create Date: 2021-04-26 16:53:47.171626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33e0aed245a'
down_revision = '8bff1d329615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('riotID', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('tagline', sa.String(length=5), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=1000), nullable=True))
    op.drop_column('user', 'tagline')
    op.drop_column('user', 'riotID')
    # ### end Alembic commands ###
