"""empty message

Revision ID: b66e5dd188a8
Revises: b33e0aed245a
Create Date: 2021-04-27 11:42:43.814916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66e5dd188a8'
down_revision = 'b33e0aed245a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_captian', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_player', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_substitute', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_substitute')
    op.drop_column('user', 'is_player')
    op.drop_column('user', 'is_captian')
    # ### end Alembic commands ###
