"""empty message

Revision ID: da5f1b1a92b5
Revises: b66e5dd188a8
Create Date: 2021-04-27 11:50:30.117436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5f1b1a92b5'
down_revision = 'b66e5dd188a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_substitute')
    op.drop_column('user', 'is_player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_player', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('is_substitute', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
