"""empty message

Revision ID: eb39c0faabd4
Revises: b33e0aed245a
Create Date: 2021-04-27 12:44:23.464087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb39c0faabd4'
down_revision = 'b33e0aed245a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('payment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'payment')
    # ### end Alembic commands ###
