# Generated by Django 3.2 on 2021-04-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20210410_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournamentRankedBy',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentDescription',
            field=models.CharField(max_length=511, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentGameName',
            field=models.CharField(choices=[('league-of-legends', 'League of Legends'), ('valorant', 'Valorant')], default='league-oflegends', max_length=31, verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentGrandFinalsMod',
            field=models.CharField(choices=[('single-match', 'Single Match'), ('skip', 'Skip')], default='single-match', max_length=31, verbose_name='Type of Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentNotifyUserWhenOpen',
            field=models.BooleanField(default=False, verbose_name='Notify User When Open'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentNotifyUserWhenTournyEnd',
            field=models.BooleanField(verbose_name='Notify User When Ended'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentPrivate',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentShowRounds',
            field=models.BooleanField(default=True, verbose_name='Show Rounds'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentSignUpCap',
            field=models.BigIntegerField(verbose_name='Sign Up Capacity'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentStartDate',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentThirdPlaceMatch',
            field=models.BooleanField(default=True, verbose_name='Third Place Match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentType',
            field=models.CharField(choices=[('round-robin', 'Round Robin'), ('single-elimination', 'Single Elimination'), ('double-Elimination', 'Double Elimination')], default='round-robin', max_length=31, verbose_name='Type of Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentURL',
            field=models.CharField(max_length=255, verbose_name='Tournament URL'),
        ),
        migrations.DeleteModel(
            name='TournamentGame',
        ),
        migrations.DeleteModel(
            name='TournamentType',
        ),
    ]
