# Generated by Django 3.2 on 2021-04-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20210411_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(default='card_images/GameRing.png', upload_to='card_images'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentURL',
            field=models.CharField(default='coolmathgames.com', max_length=255, verbose_name='Tournament URL'),
        ),
    ]
