# Generated by Django 3.2 on 2021-04-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20210411_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(default='media/GameRing.png', upload_to='media'),
        ),
    ]
