# Generated by Django 3.2 on 2021-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(default='card_images/GameRing.png', upload_to='card_images'),
        ),
    ]
