# Generated by Django 3.2 on 2021-04-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_players'),
        ('tournaments', '0009_alter_tournament_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
